apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: {{ template "acapy.fullname" . }}
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ if (lookup "v1" "Secret" .Release.Namespace (include "acapy.fullname" .)) -}}
  seed: {{ index (lookup "v1" "Secret" .Release.Namespace (include "acapy.fullname" .)).data "seed" }}
  {{- else -}}
  seed: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end -}} 